from bisect import bisect_left, bisect_right
from ..types import Entry, RangeView


class ConsolidatedOwlLogs:
    """Readonly container for consolidated owl logs."""

    _entries: list[Entry]
    _paths: list[str]
    _titles: list[str]

    def __init__(self, entries: list[Entry], paths: list[str], titles: list[str]):
        """
        Parameters
        ----------
        entries : list[Entry]
            List of owl entries
        paths : list[str]
            List of window paths used.
            Typically generated by :meth:`ConsolidatorDictionary.generate_values_list`
        titles : list[str]
            List of window titles used.
            Typically generated by :meth:`ConsolidatorDictionary.generate_values_list`
        """
        self._entries = entries
        self._paths = paths
        self._titles = titles

    def get_size(self) -> int:
        """Get the number of entries stored."""
        return len(self._entries)

    def get_entries_view(self, start_time: int, end_time: int) -> RangeView[Entry]:
        """Get a list of entries between `start_time` (inclusive)
        and `end_time` (inclusive).

        Parameters
        ----------
        start_time : int
            UNIX timestamp of the start time.
        end_time : int
            UNIX timestamp of the end time.

        Returns
        -------
        DataView[Entry]
            Readonly entries dataview.
        """
        start_i = bisect_left(
            self._entries, start_time, key=lambda x: x.get_timestamp()
        )
        end_i = bisect_right(self._entries, end_time, key=lambda x: x.get_timestamp())

        return RangeView(start_i, start_i - end_i, self._entries)

    def get_time_range(self) -> tuple[int, int]:
        """Get the time range of the entries.

        Returns
        -------
        tuple[int, int]
            Earliest log timestamp, and latest log timestamp.
        """
        earliest = self._entries[0].get_timestamp()
        latest = self._entries[-1].get_timestamp()
        return (earliest, latest)
