import argparse
import sys


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        "Owl Data Processor",
        description="Processes and manipulates log data generated by Watchful Owl",
    )
    parser.add_argument(
        "--input",
        "-i",
        action="append",
        metavar="in",
        help="Path to a '.json.log' or '.COLF' file. Glob pattern is also supported.",
    )
    parser.add_argument(
        "--output", "-o", action="append", metavar="out", help="Output path."
    )
    return parser


def main():
    parser = create_parser()
    args = parser.parse_args(sys.argv[1:])


if __name__ == "__main__":
    main()
