import argparse

from .consolidator import ConsolidatorDictionary


def main():
    parser = argparse.ArgumentParser(
        "Owl Data Processor",
        description="Processes and manipulates log data generated by Watchful Owl",
    )
    parser.add_argument(
        "--input",
        "-i",
        action="append",
        metavar="in",
        help="Path to a '.json.log' or '.COLF' file. Glob pattern is also supported.",
    )
    parser.add_argument(
        "--output", "-o", action="append", metavar="out", help="Output path."
    )
    args = parser.parse_args()

    limb_dict = ConsolidatorDictionary()
    limbs = []
    limbs.append(limb_dict.use_value("head"))
    limbs.append(limb_dict.use_value("arm"))
    limbs.append(limb_dict.use_value("arm"))
    limbs.append(limb_dict.use_value("leg"))
    limbs.append(limb_dict.use_value("leg"))
    print(limbs)
    limbs_value_list = limb_dict.generate_values_list()
    print(limbs_value_list[limbs[2]])


if __name__ == "__main__":
    main()
